[package]
name = "tetris-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
termion = "1.5.6"
log = "0.4"
log4rs = "1"
rand = "0.8.4"
confy = "0.4.0"
serde = { version = "1.0", features = [ "derive" ] }
big_num = "0.1.0"
libmath = "0.2.1"
