[package]
name = "tetris-cli"
version = "21.411.1"
edition = "2021"

[dependencies]
termion = "1.5.6"
rand = "0.8.4"
confy = "0.4.0"
serde = { version = "1.0", features = [ "derive" ] }
big_num = "0.1.0"
libmath = "0.2.1"
