appenders:
  log_output:
    kind: file
    path: "tetris-cli.log"
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} - {l}: {m}{n})}"
root:
  level: info
  appenders:
    - log_output